### ISSUE TITLE
New rule: Detect links to non-existing sections

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review-documentation#3]
**What the rule should do:**

Detect links to non-existing sections/functions/types in the documentation, in the README and in the modules.

**What problems does it solve:**

This would help maintaining documentation (it would notice outdated documentation), and notice when you add a link with an error in the path to the section

I don't think the rule should provide an automatic fix, but I think it could provide suggestions ("Did you mean '#init'?")

**Example of things the rule would report:**

```elm
A [section](#section), if that section does not exist
```

**Example of things the rule would not report:**

```md
# section

A [section](#section)

A [section](./ModuleName#section) from another file, if it exists in that file.

Link to image [](./image.png)
```
```elm
{-|
@docs init

Look at the [init](#init) function
-}

{-| the init function -}
init : Model
init = 1
```

**When (not) to enable this rule:**

If you are working on an application and it has no documentation?

**I am looking for:**

- A good rule name
- Someone to implement it (I can provide help and guidance)

(More unorganized thoughts over at https://trello.com/c/BKfdmp8v/2-noinvalidreferences-noinvalidlinks-make-sure-that-all-references-to-sections-are-valid)

**Comment by lue-bird** [comment]
As you suggested: Please yoink [lue-bird/elm-review-links-point-to-existing-package-members](https://github.com/lue-bird/elm-review-links-point-to-existing-package-members)'s rule for the module/definition link part.
